name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
     - name: Deploy to server
       uses: garygrossgarten/github-action-ssh@release
       with:
         command: bash deploySiteDev.sh
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER }}
         privateKey: ${{ secrets.PRIVATE_KEY }}
       env:
         CI: true
